config/routes.rb
Rails.application.routes.draw do

  get 'entries/favorites'

  root 'entries#index'
  resources :feeds do
    get :refresh_all, on: :collection
    get :refresh, on: :member
    get :download_newest, on: :member
  end
  resources :entries, only: [:index, :show, :favorites]

  resources :favorite_entries, only: [:create, :destroy]  

  devise_for :users

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :feed
  belongs_to :user

  def self.create_entry_from_feed(entry)
    new_entry = Entry.new(title: entry.title,
                          author: entry.author,
                          content: check_content(entry),
                          published: entry.published,
                          url: entry.url,
                         )
    new_entry
  end

  private

  def self.check_content(entry)
    return entry.content if entry.content
    return entry.summary if entry.summary
  end
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :favorited, polymorphic: true
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  belongs_to :user
  has_many :entries, dependent: :destroy
  validates :url, presence: true
  after_create :download_entries_after_feed_create

  #grab each feed
  #update feed articles - download_entries_after_feed_create

  def update_feed!
    @newest_entry = entries.order(published: :desc).first

    download_success_date = lambda { |url, feed|
      feed.entries.each do |entry|
         next unless !@newest_entry || entry.published > @newest_entry.published
         add_new_entry_from_feed(entry)
      end
    }
    Feedjira::Feed.fetch_and_parse(
      url,
      on_success: download_success_date,
      on_failure: download_failure
    )
  end

  def download_all_entries!
    Feedjira::Feed.fetch_and_parse(
      url,
      on_success: download_success,
      on_failure: download_failure
    )
  end

  def download_newest_entries!(number)
    return false if number == 0
    on_success_number = lambda { |url, feed|
      feed.entries[0..number - 1].each do |entry|
        add_new_entry_from_feed(entry)
      end
    }
    feed = Feedjira::Feed.fetch_and_parse(
      url,
      on_success: on_success_number,
      on_failure: download_failure
    )
  end

  def download_newest_entry!
    download_newest_entries!(1)[0]
  end

  def self.update_all_feeds
    Feed.all.each do |feed|
      feed.update_feed!
    end
  end

  def download_entries_after_feed_create
    download_newest_entries!(20)
  end

  private

  def add_new_entry_from_feed(entry)
    db_entry = Entry.create_entry_from_feed(entry)
    db_entry.feed_id = id
    db_entry.save
  end

  def download_success
    lambda { |url, feed|
      feed.entries.each do |entry|
        add_new_entry_from_feed(entry)
      end
    }
  end

  def download_failure
    lambda { |curl, err|
      logger.error "Downloading #{curl} failed due to #{error}"
    }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :feeds, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_entries, through: :favorites, source: :favorited, source_type: 'Entry'

  def entries
    entries = []
    self.feeds.each do |feed|
      feed.entries.each do |entry|
        entries << entry
      end
    end
	entries
  end
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def call_rake(task, options = {})
    logfile = "#{Rails.root}/log/rake.log"
    options[:rails_env] ||= Rails.env
    args = options.map { |n, v| "#{n.to_s.upcase}='#{v}'" }
    system "/usr/bin/rake #{task} #{args.join(' ')} >> #{logfile} 2>> #{logfile} &"
  end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
   @entries = Entry.all.order(published: :desc)
  end

  def favorites
    @entries = current_user.favorite_entries
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    @entry = Entry.find(params[:id])
    @entry.update_attributes(read: true)
    @entry
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:url, :title, :author, :content, :published, :feed_id)
    end
end

app/controllers/favorite_entries_controller.rb
class FavoriteEntriesController < ApplicationController
  before_action :set_entry
  
  def create
    if Favorite.create(favorited: @entry, user: current_user)
      redirect_to @entry, notice: 'Article has been favorited'
    else
      redirect_to @entry, alert: 'Something went wrong...'
    end
  end
  
  def destroy
    Favorite.where(favorited_id: @entry.id, user_id: current_user.id).first.destroy
    redirect_to @entry, notice: 'Entry is no longer in favorites'
  end
  
  private
  
  def set_entry
    @entry = Entry.find(params[:entry_id] || params[:id])
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :authenticate_user!

  require 'rake'

  def index
    @feeds = Feed.where(user: current_user).order("created_at DESC")
  end

  def show
    @feed = Feed.find(params[:id])
    @entries = @feed.entries.all.order(published: :asc)
  end

  def new
    @feed = Feed.new
  end

  def create
    @feed = Feed.new(feed_params)
    @feed.user_id = current_user.id
    
    respond_to do |format|
      if @feed.save
        format.html { redirect_to feeds_path, notice: 'Subscription was successfully created.' }
        format.json { render action: 'show', status: :created, location: @feed }
      else
        format.html { render action: 'new' }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @feed = Feed.find(params[:id])
    @feed.update(feed_params)
    redirect_to feed_path(@feed)
  end

  def destroy
     @feed = Feed.find(params[:id])
     @feed.destroy
     respond_to do |format|
     format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
     format.json { head :no_content }
   end
  end

def refresh
    call_rake :update_feed, feed_id: params[:id].to_i
    flash[:notice] = 'Updated Feed'
    redirect_to feeds_path
  end

  def download_newest
    call_rake :download_newest, feed_id: params[:id].to_i
    flash[:notice] = 'Finished downloading newest entries for that feed'
    redirect_to feeds_path
  end

  private

  def feed_params
    params.require(:feed).permit(:url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/entries/favorites.html.erb
<% if user_signed_in? %>
  <% if user_signed_in? and current_user.favorite_entries == [] %>
    <h4 class="highlight">You have not favorited any articles yet. Go read through some more <%= link_to "articles", entries_path, class:"btn-link" %> to find a good one!</h4>
  <%else%>
    <h1><span class="glyph glyphicon-star"></span> My Favorite Entries <span class="glyph glyphicon-star"></span></h1>

    <table class="table table-striped" style="width:100%">
      <thead>
        <tr class="row">
          <th class="col-xs-4 col-sm-4 col-md-4 col-lg-4">Title</th>
          <th class="col-xs-5 col-sm-5 col-md-5 col-lg-5">Content</th>
          <th class="col-xs-1 col-sm-1 col-md-1 col-lg-1">Original</th>
          <th class="col-xs-2 col-sm-2 col-md-2 col-lg-2">Published</th>
        </tr>
      </thead>

      <tbody>
        <% current_user.favorite_entries.each do |entry| %>
          <tr class="row">
            <td class="col-xs-4 col-sm-4 col-md-4 col-lg-4"><%= link_to entry.title.titleize.truncate(100), entry, class:"btn-link", style:"color:#{000000};font-weight:bold;" %></td>
            <td class="col-xs-5 col-sm-5 col-md-5 col-lg-5"><%= link_to entry.content.capitalize.truncate(250), entry, class:"btn-link" %></td>
            <td class="col-xs-1 col-sm-1 col-md-1 col-lg-1"><%= link_to "Link", (entry.url), class:"btn-link" %></td>
            <td class="col-xs-2 col-sm-2 col-md-2 col-lg-2"><%= entry.published.strftime("%m/%d/%Y %I:%M%P") %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
    <br>
<% else %>
  <%= render 'layouts/default' %>
<% end %>

app/views/entries/index.html.erb
<% if user_signed_in? %>
  <% if user_signed_in? and current_user.feeds == [] %>
    <h4 class="highlight">There are no active subscriptions at this time. What are you waiting for? Add some on your <%= link_to "subscriptions", new_feed_path, class:"btn-link" %> page.</h4>
  <%else%>
    <h1>Recent Entries</h1>

    <table class="table table-striped" style="width:100%">
      <thead>
        <tr class="row">
          <th class="col-xs-1 col-sm-1 col-md-1 col-lg-1">Read</th>  
          <th class="col-xs-3 col-sm-3 col-md-3 col-lg-3">Title</th>
          <th class="col-xs-5 col-sm-5 col-md-5 col-lg-5">Content</th>
          <th class="col-xs-1 col-sm-1 col-md-1 col-lg-1">Original</th>
          <th class="col-xs-2 col-sm-2 col-md-2 col-lg-2">Published</th>
        </tr>
      </thead>

      <tbody>
        <% current_user.entries.each do |entry| %>
          <tr class="row">
            <td class="col-xs-1 col-sm-1 col-md-1 col-lg-1"><%= "<span class=\"check glyphicon-ok\"></span>".html_safe if entry.read == true %></td>
            <td class="col-xs-3 col-sm-3 col-md-3 col-lg-3"><%= link_to entry.title.titleize.truncate(100), entry, class:"btn-link", style:"color:#{000000};font-weight:bold;" %></td>
            <td class="col-xs-5 col-sm-5 col-md-5 col-lg-5"><%= link_to entry.content.capitalize.truncate(250), entry, class:"btn-link" %></td>
            <td class="col-xs-1 col-sm-1 col-md-1 col-lg-1"><%= link_to "Link", (entry.url), class:"btn-linked", target:"blank" %></td>
            <td class="col-xs-2 col-sm-2 col-md-2 col-lg-2"><%= entry.published.strftime("%m/%d/%Y %I:%M%P") %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
    <br>
<% else %>
  <%= render 'layouts/default' %>
<% end %>

app/views/entries/show.html.erb
<h3>
	<%= render 'layouts/favorite' %>
	<%= @entry.title.titleize %>
</h3>

<p class="highlight">
  <%= @entry.content.capitalize %>
</p>

<p>
  <strong>
    <%= link_to "Original Page", (@entry.url), class:"btn-link", target:"blank" %>
  </strong>
</p>

<p>
  <strong>Published:</strong>
  <%= @entry.published.strftime("%m/%d/%Y %I:%M%P") %>
</p>

<%= link_to 'Back', entries_path, class:"btn btn-default" %>

app/views/feeds/_form.html.erb
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if user_signed_in? %>
    <div class="form-group">
      <%= f.label :paste_rss_url_below %><br>
      <%= f.text_area :url, class:"form-control", placeholder:"Feed Me More!" %>
    </div>
    <div class="actions">
      <%= f.submit class:"btn btn-default" %>
    </div>
  <% else %>
    <%= render 'layouts/default' %>
  <% end %>
<% end %>

app/views/feeds/index.html.erb
<% if user_signed_in? %>
  <h1>My subscriptions</h1>
  <% if user_signed_in? and current_user.feeds == [] %>
    <h4 class="highlight">There are no active subscriptions at this time. What are you waiting for? Add some using the button below!</h4>
    <%else%>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Subscription URLs</th>
          </tr>
        </thead>

        <tbody>
          <% @feeds.each do |feed| %>
            <tr>
              <td>
                <h5>
                  <%= feed.url %>
                </h5>
              </td>
              <% if (user_signed_in?) && (current_user == feed.user) %>
                <td>
                  <%= link_to "<span class=\"glyphicon glyphicon-refresh\"></span>".html_safe, [:refresh, feed], class: 'action btn btn-default', title: 'refresh feed' %>
                </td>
                <td>
                  <%= link_to 'Delete', feed, method: :delete, data: { confirm: 'Are you sure? The subscription and all associated stared articles will be destroyed!' }, class:"btn btn-danger" %>
                </td>
            <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>

  <br>

  <%= link_to 'New Feed', new_feed_path, class:"btn btn-default" %>
<% else %>
  <%= render 'layouts/default' %>
<% end %>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path, class:"btn btn-link" %>

app/views/feeds/show.html.erb
<p>
  <strong>Url:</strong>
  <%= @feed.url %>
</p>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/layouts/_bootstrap.html.erb
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

<script src="//code.jquery.com/jquery-2.1.1.min.js"></script>

app/views/layouts/_default.html.erb
<h3 class="highlight">Welcome to itFEEDS, an awesome new RSS reader! Please <%= link_to "sign in", new_user_session_path, class:"btn-link" %> to add subscriptions. </h3>
  <div class="row">
    <div class="col-xs-12 col-xs-offset-2 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4 col-lg-4 col-lg-offset-4">
      <%= image_tag("60165.png") %>
    </div>
  </div>

app/views/layouts/_favorite.html.erb
<% unless current_user.favorite_entries.exists?(id: @entry.id) %>
<%= link_to "<span class=\"glyph glyphicon-star-empty\"></span>".html_safe, favorite_entries_path(entry_id: @entry), method: :post %>
<% else %>
<%= link_to "<span class=\"glyph glyphicon-star\"></span>".html_safe, favorite_entry_path(@entry), method: :delete %>
<% end %>

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-inverse navbar-fixed-bottom">
  <div class="container">
    
  </div>
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <%= image_tag("favicon.png", class:"logo")%>
        <%= link_to "itFEEDS", root_path, class:"navbar-brand", style:"font-size: 22px;" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "MyFeed", root_path %></li>
          <li><%= link_to "My Subscriptions", feeds_path %></li>
          <li><%= link_to "My Favorites", entries_favorites_path %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "Profile", edit_user_registration_path %></li>
        <% else %>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <li><%= link_to "Sign in", new_user_session_path %></li>
            <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<html>
<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <title>itFEED</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= render 'layouts/bootstrap' %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/bootstrap' %>
</head>

<body>
<%= render 'layouts/nav' %>
<div class="container" style="min-height: 34.5em;">
	<% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %>
<%= yield %>
</div> 
<br>
<br>
<br>
                      
</body>
</html>